version: '3'
services:
  datacollector:
    build:
      context: ./docker
      dockerfile: Dockerfile-datacollector
    volumes:
      - ./dice:/opt/dice
      - ./data:/data
    ports:
      - "8777:8777"
    environment:
      - DATA_RESULTS_FILE=/data/dice-results.csv
  exprandom:
    build:
      context: ./docker
      dockerfile: Dockerfile-experiment
    volumes:
      - ./dice:/opt/dice
    depends_on:
      - datacollector
    environment:
      - DATA_COLLECTOR_HOSTNAME=datacollector
      - SOFT_STOP_SECONDS=72000
      - DIE_BIAS=random
  expgambler:
    build:
      context: ./docker
      dockerfile: Dockerfile-experiment
    volumes:
      - ./dice:/opt/dice
    depends_on:
      - datacollector
    environment:
      - DATA_COLLECTOR_HOSTNAME=datacollector
      - SOFT_STOP_SECONDS=72000
      - DIE_BIAS=gambler
